import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import ".././globals.css";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { AppSidebar } from "@/components/app-sidebar";
import { BookableProvider } from "@/context/BookableContext";
import { AuthProvider } from "@/context/AuthContext";
import { SlotProvider } from "@/context/SlotContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  <html lang="en">
    <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`} 
      >
      <AuthProvider>
        <SlotProvider>
          <BookableProvider>
              <SidebarProvider>
                <AppSidebar />
                <main className="flex-1 p-6">
                  <SidebarTrigger />
                  {children}
                </main>
              </SidebarProvider>
            </BookableProvider>
          </SlotProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
